services:
  mysql:
    image: mysql:8.0
    container_name: hadar-pub-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    ports:
      - "3308:3306"

    volumes:
      - hadar_mysql_data:/var/lib/mysql
      - ../database/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h 127.0.0.1 -u root -p${MYSQL_ROOT_PASSWORD} --silent"
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile

    image: hadar-pub-backend
    container_name: hadar-pub-backend
    restart: unless-stopped

    depends_on:
      mysql:
        condition: service_healthy

    environment:
      ENVIRONMENT: production
      PORT: 4000

      MYSQL_HOST: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

      JWT_SECRET: ${JWT_SECRET}

      BASE_IMAGE_URL: http://localhost:4000/api/products/images/

    ports:
      - "4000:4000"

    volumes:
        - ./storage/products:/app/storage/products
        - ./storage/events:/app/storage/events
        - ./storage/customers:/app/storage/customers
        - ./storage/videos:/app/storage/videos

  adminer:
    image: adminer
    container_name: hadar-pub-adminer
    restart: unless-stopped

    depends_on:
      mysql:
        condition: service_healthy

    ports:
      - "8080:8080"

volumes:
  hadar_mysql_data:
   