CREATE TABLE suppliers (
    id_supplier INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

    supplier_name VARCHAR(200) NOT NULL,
    supplier_email VARCHAR(200) NOT NULL UNIQUE,
    supplier_mobile VARCHAR(30) NOT NULL UNIQUE,
    supplier_address VARCHAR(255) NOT NULL,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP
);